#!/bin/bash
#SBATCH --job-name=hwang_heart
#SBATCH --partition=zen3_0512_a100x2 
#SBATCH --qos=zen3_0512_a100x2      
#SBATCH --account=p72515
#SBATCH --gres=gpu:1
#SBATCH --ntasks=1
#SBATCH --time=00:20:00
#SBATCH --cpus-per-task=1    # Adjust CPU allocation
#SBATCH --output=/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/logs/output_%j.out   # Standard output file (with unique job ID)
#SBATCH --error=/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/logs/error_%j.err     # Standard error file (with unique job ID)
module load cuda/11.8.0-gcc-12.2.0-bplw5nu
source /home/fs72515/nadja_g/.bashrc
conda activate Lion
nvidia-smi


w="psnr_model_weights.pth"

python predict.py --weight $w --angles 512 --noise_sigma 2 --noise_intensity 1 --dat 'z' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data_Heart/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/Model_Weights/Noise_gauss_sigma_2.0_1.0_batchsize_4_Gaussian_Method_DataDomain_MSE_EMD_alpha_1_learning_rate_7.5e-05_angles_512" 
python predict.py --weight $w --angles 512 --noise_sigma 2 --noise_intensity 1 --dat 'z' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data_Heart/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/Model_Weights/Noise_gauss_sigma_2.0_1.0_batchsize_4_Gaussian_Method_DataDomain_MSE_Inference_EMD_alpha_1_learning_rate_7.5e-05_angles_512" 
python predict.py --weight $w --angles 512 --noise_sigma 2 --noise_intensity 1 --dat 'z' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data_Heart/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/Model_Weights/Noise_gauss_sigma_2.0_1.0_batchsize_4_Gaussian_Method_DataDomain_MSE_Inference_EMD_Sobolev_alpha_1_learning_rate_7.5e-05_angles_512" 
python predict.py --weight $w  --angles 512 --noise_sigma 3 --noise_intensity 1 --dat 'z' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data_Heart/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/Model_Weights/Noise_gauss_sigma_3.0_1.0_batchsize_4_Gaussian_Method_DataDomain_MSE_EMD_alpha_1_learning_rate_7.5e-05_angles_512" 
python predict.py --weight $w --angles 512 --noise_sigma 3 --noise_intensity 1 --dat 'z' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data_Heart/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/Model_Weights/Noise_gauss_sigma_3.0_1.0_batchsize_4_Gaussian_Method_DataDomain_MSE_Inference_EMD_alpha_1_learning_rate_7.5e-05_angles_512" 
python predict.py  --weight $w --angles 512 --noise_sigma 3 --noise_intensity 1 --dat 'z' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data_Heart/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/Model_Weights/Noise_gauss_sigma_3.0_1.0_batchsize_4_Gaussian_Method_DataDomain_MSE_Inference_EMD_Sobolev_alpha_1_learning_rate_7.5e-05_angles_512" 
python predict.py --weight $w --angles 512 --noise_sigma 5 --noise_intensity 1 --dat 'z' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data_Heart/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/Model_Weights/Noise_gauss_sigma_5.0_1.0_batchsize_4_Gaussian_Method_DataDomain_MSE_EMD_alpha_1_learning_rate_7.5e-05_angles_512" 
python predict.py --weight $w --angles 512 --noise_sigma 5 --noise_intensity 1 --dat 'z' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data_Heart/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/Model_Weights/Noise_gauss_sigma_5.0_1.0_batchsize_4_Gaussian_Method_DataDomain_MSE_Inference_EMD_alpha_1_learning_rate_7.5e-05_angles_512" 
python predict.py --weight $w --angles 512 --noise_sigma 5 --noise_intensity 1 --dat 'z' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data_Heart/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/Model_Weights/Noise_gauss_sigma_5.0_1.0_batchsize_4_Gaussian_Method_DataDomain_MSE_Inference_EMD_Sobolev_alpha_1_learning_rate_7.5e-05_angles_512" 


python predict.py --weight $w --angles 512 --noise_sigma 2 --noise_intensity 1 --dat 'y' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data_Heart/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/Model_Weights/Noise_gauss_sigma_2.0_1.0_batchsize_4_Gaussian_Method_DataDomain_MSE_EMD_alpha_1_learning_rate_7.5e-05_angles_512" 
python predict.py --weight $w --angles 512 --noise_sigma 2 --noise_intensity 1 --dat 'y' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data_Heart/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/Model_Weights/Noise_gauss_sigma_2.0_1.0_batchsize_4_Gaussian_Method_DataDomain_MSE_Inference_EMD_alpha_1_learning_rate_7.5e-05_angles_512" 
python predict.py --weight $w --angles 512 --noise_sigma 2 --noise_intensity 1 --dat 'y' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data_Heart/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/Model_Weights/Noise_gauss_sigma_2.0_1.0_batchsize_4_Gaussian_Method_DataDomain_MSE_Inference_EMD_Sobolev_alpha_1_learning_rate_7.5e-05_angles_512" 
python predict.py --weight $w --angles 512 --noise_sigma 3 --noise_intensity 1 --dat 'y' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data_Heart/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/Model_Weights/Noise_gauss_sigma_3.0_1.0_batchsize_4_Gaussian_Method_DataDomain_MSE_EMD_alpha_1_learning_rate_7.5e-05_angles_512" 
python predict.py --weight $w --angles 512 --noise_sigma 3 --noise_intensity 1 --dat 'y' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data_Heart/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/Model_Weights/Noise_gauss_sigma_3.0_1.0_batchsize_4_Gaussian_Method_DataDomain_MSE_Inference_EMD_alpha_1_learning_rate_7.5e-05_angles_512" 
python predict.py  --weight $w --angles 512 --noise_sigma 3 --noise_intensity 1 --dat 'y' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data_Heart/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/Model_Weights/Noise_gauss_sigma_3.0_1.0_batchsize_4_Gaussian_Method_DataDomain_MSE_Inference_EMD_Sobolev_alpha_1_learning_rate_7.5e-05_angles_512" 
python predict.py --weight $w --angles 512 --noise_sigma 5 --noise_intensity 1 --dat 'y' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data_Heart/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/Model_Weights/Noise_gauss_sigma_5.0_1.0_batchsize_4_Gaussian_Method_DataDomain_MSE_EMD_alpha_1_learning_rate_7.5e-05_angles_512" 
python predict.py --weight $w --angles 512 --noise_sigma 5 --noise_intensity 1 --dat 'y' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data_Heart/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/Model_Weights/Noise_gauss_sigma_5.0_1.0_batchsize_4_Gaussian_Method_DataDomain_MSE_Inference_EMD_alpha_1_learning_rate_7.5e-05_angles_512" 
python predict.py --weight $w --angles 512 --noise_sigma 5 --noise_intensity 1 --dat 'y' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data_Heart/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Heart_Final/Model_Weights/Noise_gauss_sigma_5.0_1.0_batchsize_4_Gaussian_Method_DataDomain_MSE_Inference_EMD_Sobolev_alpha_1_learning_rate_7.5e-05_angles_512" 

#python predict.py -l "DataDomain_MSE_EMD" --angles 512 --noise_type "gauss" --learning_rate 7e-5 --noise_intensity 5 --noise_sigma 5 --batch_size 4 --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_final/Model_Weights/" 
python predict.py --weight $w --angles 512 --noise_sigma 2 --noise_intensity 5 --dat 'z' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/Model_Weights/Noise_gauss_sigma_2.0_5.0_batchsize_4_Gaussian_Method_DataDomain_MSE_EMD_alpha_1_learning_rate_0.0001_angles_512" 
python predict.py --weight $w --angles 512 --noise_sigma 2 --noise_intensity 5 --dat 'z' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/Model_Weights/Noise_gauss_sigma_2.0_5.0_batchsize_4_Gaussian_Method_DataDomain_MSE_Inference_EMD_alpha_1_learning_rate_0.0001_angles_512" 
python predict.py --weight $w --angles 512 --noise_sigma 2 --noise_intensity 5 --dat 'z' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/Model_Weights/Noise_gauss_sigma_2.0_5.0_batchsize_4_Gaussian_Method_DataDomain_MSE_Inference_EMD_Sobolev_alpha_1_learning_rate_0.0001_angles_512" 
python predict.py --weight $w  --angles 512 --noise_sigma 3 --noise_intensity 5 --dat 'z' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/Model_Weights/Noise_gauss_sigma_3.0_5.0_batchsize_4_Gaussian_Method_DataDomain_MSE_EMD_alpha_1_learning_rate_0.0001_angles_512" 
python predict.py --weight $w --angles 512 --noise_sigma 3 --noise_intensity 5 --dat 'z' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/Model_Weights/Noise_gauss_sigma_3.0_5.0_batchsize_4_Gaussian_Method_DataDomain_MSE_Inference_EMD_alpha_1_learning_rate_0.0001_angles_512" 
python predict.py --weight $w --angles 512 --noise_sigma 3 --noise_intensity 5 --dat 'z' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/Model_Weights/Noise_gauss_sigma_3.0_5.0_batchsize_4_Gaussian_Method_DataDomain_MSE_Inference_EMD_Sobolev_alpha_1_learning_rate_0.0001_angles_512" 
python predict.py --weight $w --angles 512 --noise_sigma 5 --noise_intensity 5 --dat 'z' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/Model_Weights/Noise_gauss_sigma_5.0_5.0_batchsize_4_Gaussian_Method_DataDomain_MSE_EMD_alpha_1_learning_rate_0.0001_angles_512" 
python predict.py --weight $w --angles 512 --noise_sigma 5 --noise_intensity 5 --dat 'z' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/Model_Weights/Noise_gauss_sigma_5.0_5.0_batchsize_4_Gaussian_Method_DataDomain_MSE_Inference_EMD_alpha_1_learning_rate_0.0001_angles_512" 
python predict.py --weight $w --angles 512 --noise_sigma 5 --noise_intensity 5 --dat 'z' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/Model_Weights/Noise_gauss_sigma_5.0_5.0_batchsize_4_Gaussian_Method_DataDomain_MSE_Inference_EMD_Sobolev_alpha_1_learning_rate_0.0001_angles_512" 


python predict.py --weight $w --angles 512 --noise_sigma 2 --noise_intensity 5 --dat 'y' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/Model_Weights/Noise_gauss_sigma_2.0_5.0_batchsize_4_Gaussian_Method_DataDomain_MSE_EMD_alpha_1_learning_rate_0.0001_angles_512" 
python predict.py --weight $w --angles 512 --noise_sigma 2 --noise_intensity 5 --dat 'y' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/Model_Weights/Noise_gauss_sigma_2.0_5.0_batchsize_4_Gaussian_Method_DataDomain_MSE_Inference_EMD_alpha_1_learning_rate_0.0001_angles_512" 
python predict.py --weight $w --angles 512 --noise_sigma 2 --noise_intensity 5 --dat 'y' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/Model_Weights/Noise_gauss_sigma_2.0_5.0_batchsize_4_Gaussian_Method_DataDomain_MSE_Inference_EMD_Sobolev_alpha_1_learning_rate_0.0001_angles_512" 
python predict.py --weight $w --angles 512 --noise_sigma 3 --noise_intensity 5 --dat 'y' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/Model_Weights/Noise_gauss_sigma_3.0_5.0_batchsize_4_Gaussian_Method_DataDomain_MSE_EMD_alpha_1_learning_rate_0.0001_angles_512" 
python predict.py --weight $w --angles 512 --noise_sigma 3 --noise_intensity 5 --dat 'y' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/Model_Weights/Noise_gauss_sigma_3.0_5.0_batchsize_4_Gaussian_Method_DataDomain_MSE_Inference_EMD_alpha_1_learning_rate_0.0001_angles_512" 
python predict.py --weight $w --angles 512 --noise_sigma 3 --noise_intensity 5 --dat 'y' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/Model_Weights/Noise_gauss_sigma_3.0_5.0_batchsize_4_Gaussian_Method_DataDomain_MSE_Inference_EMD_Sobolev_alpha_1_learning_rate_0.0001_angles_512" 
python predict.py --weight $w --angles 512 --noise_sigma 5 --noise_intensity 5 --dat 'y' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/Model_Weights/Noise_gauss_sigma_5.0_5.0_batchsize_4_Gaussian_Method_DataDomain_MSE_EMD_alpha_1_learning_rate_0.0001_angles_512" 
python predict.py --weight $w --angles 512 --noise_sigma 5 --noise_intensity 5 --dat 'y' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/Model_Weights/Noise_gauss_sigma_5.0_5.0_batchsize_4_Gaussian_Method_DataDomain_MSE_Inference_EMD_alpha_1_learning_rate_0.0001_angles_512" 
python predict.py --weight $w --angles 512 --noise_sigma 5 --noise_intensity 5 --dat 'y' --datadir '/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Data/' --outputdir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/" --weights_dir "/gpfs/data/fs72515/nadja_g/Noisier2Inverse/Noisier2Inverse/Results_Paper_Nuts_Final/Model_Weights/Noise_gauss_sigma_5.0_5.0_batchsize_4_Gaussian_Method_DataDomain_MSE_Inference_EMD_Sobolev_alpha_1_learning_rate_0.0001_angles_512" 
